name: Notification on PR

on:
  pull_request:
    branches: [ main, team/react ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1160910886848954418/AkUpK5d9IDtWuRkVguBxxoIZuAe21kMUOjNG1vZHi2w-5eNR9i0HvyccG09k3VjJuxcF
        DISCORD_USERNAME: PR bot
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new PR has been created at front-project'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1160910886848954418/AkUpK5d9IDtWuRkVguBxxoIZuAe21kMUOjNG1vZHi2w-5eNR9i0HvyccG09k3VjJuxcF
      uses: Ilshidur/action-discord@master
